# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 0406店铺签到有礼+关注有礼

on:
  workflow_dispatch:
  schedule:
    - cron: '57 18,12 * * *'
  repository_dispatch:
    types: 店铺签到相关
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: hajiuhajiu/jdsign1112
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '签到'
        run: |

          curl https://github.com/Nightmare-Serene/masadora-gd-center-tracker/blob/master/config.js
          sleep 5
          curl https://github.com/Nightmare-Serene/masadora-gd-center-tracker/blob/master/index.js
          sleep 5
          curl https://github.com/Nightmare-Serene/masadora-gd-center-tracker/blob/master/push.js
          sleep 5
                  
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
